### PR TITLE
Update class-customer-chat-for-facebook-public.php

### PR DESCRIPTION
**Pull request by mav2287**
This will allow for using the sdk functions. For example using a button on the site to pop up the chat.

### CODE REVIEW

**Comment by ThatGuySam** [comment]
This is interesting but it does directly affect the main function of the plugin that every is using so I'll have to do some manual testing. 

Can you provide any articles or documentation about this?

**Comment by mav2287** [comment]
Essentially it contains all the same stuff as the other file EXCEPT it adds the JS SDK so you can use FB.CustomerChat.show or FB.CustomerChat.hide and so on and so forth to do stuff. I use it on my site for a button that says "Start Chatting With Us". When you hit the button it uses the SDK to popup the chat window.

You should see no change between what you have now and the SDK except added functionality The file size difference is so small it should have no affects on page speed.

Here is a link to the info https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin/sdk

**Comment by mav2287** [comment]
It's been over a month... is there any decision on getting this into the source?

**Comment by mav2287** [comment]
Also it wouldn't be much work to just make it an option on which one to use if compatibility is a concern

**Comment by ThatGuySam** [comment]
Yeh, sorry. I've been super slammed with client work. Your pull seems fine I just need to find the time merge and deploy it.

**Comment by mav2287** [comment]
No worries, I can totally relate. We have been slammed too.

**Pull request merged**
